default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= Figaro.env.db_pool %>
  timeout: 5000
  schema_search_path: public

development:
  <<: *default
  database:  flats
  host: localhost

test:
  <<: *default
  database: flats_test
  username: <%= Figaro.env.username %>
  password: <%= Figaro.env.password %>

production:
  <<: *default
  database: <%= Figaro.env.database %>
  username: <%= Figaro.env.username %>
  password: <%= ENV['FLATS_API_DATABASE_PASSWORD'] %>
